name: CI Workflow

on:
  push:
    branches:
      - main  # Exécute le workflow à chaque push sur main

  pull_request:
    branches:
      - main  # Exécute sur les pull requests vers main

jobs:
  test:
    runs-on: windows-latest  # Corrigé: espace ajouté

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Version mise à jour

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run tests
        run: pytest



